steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rich-implement-431912-i3/first_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rich-implement-431912-i3/first_app']
